version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: installing-npm
          command: npm install
      - run:
          name: npm testing
          command: npm test

  #Þarf að run puppiter test líka ef við náum því  
  # push to heroku https://circleci.com/integrations/heroku/



