version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'npm install'
      - run:
          name: update-pdf
          command: 'npm run convertmdtopdf'
      - run:
          name: test npm
          command: 'npm test'
